"""Pydantic models for the Kalshi Klear (SCM) API."""

from __future__ import annotations

from kalshi.perps.klear.models.common import Error
from kalshi.perps.klear.models.margin import (
    AssetClassLiteral,
    AssetClassSettlementEstimate,
    CreateMarginSubtraderGroupRequest,
    CreateMarginSubtraderGroupResponse,
    GetActiveMarginObligationResponse,
    GetActiveMarginObligationsResponse,
    GetGuarantyFundBalanceResponse,
    GetMarginReportsResponse,
    GetMarginSubtraderGroupsResponse,
    GetObligationHistoryResponse,
    GetSettlementBalanceHistoryResponse,
    GetSettlementBalanceResponse,
    GetSettlementBalanceWithdrawalResponse,
    GetSettlementEstimateByAssetClassResponse,
    GetSettlementEstimateResponse,
    MaintenanceMarginDetail,
    MarginReport,
    MarginReportTypeLiteral,
    MarginSubtraderGroup,
    MarketSettlementEstimate,
    ObligationEntry,
    ObligationReceiveInfo,
    SettlementBalanceHistoryEntry,
    SettlementDetail,
    SettlementEstimate,
    UpdateMarginSubtraderGroupRequest,
    WithdrawalStatusLiteral,
    WithdrawSettlementBalanceRequest,
    WithdrawSettlementBalanceResponse,
)

__all__ = [
    "AssetClassLiteral",
    "AssetClassSettlementEstimate",
    "CreateMarginSubtraderGroupRequest",
    "CreateMarginSubtraderGroupResponse",
    "Error",
    "GetActiveMarginObligationResponse",
    "GetActiveMarginObligationsResponse",
    "GetGuarantyFundBalanceResponse",
    "GetMarginReportsResponse",
    "GetMarginSubtraderGroupsResponse",
    "GetObligationHistoryResponse",
    "GetSettlementBalanceHistoryResponse",
    "GetSettlementBalanceResponse",
    "GetSettlementBalanceWithdrawalResponse",
    "GetSettlementEstimateByAssetClassResponse",
    "GetSettlementEstimateResponse",
    "MaintenanceMarginDetail",
    "MarginReport",
    "MarginReportTypeLiteral",
    "MarginSubtraderGroup",
    "MarketSettlementEstimate",
    "ObligationEntry",
    "ObligationReceiveInfo",
    "SettlementBalanceHistoryEntry",
    "SettlementDetail",
    "SettlementEstimate",
    "UpdateMarginSubtraderGroupRequest",
    "WithdrawSettlementBalanceRequest",
    "WithdrawSettlementBalanceResponse",
    "WithdrawalStatusLiteral",
]
