"""Kalshi Perps (margin) API — standalone client surface.

The Perps (perpetual futures / margin) API lives on a **separate host** from the
prediction (event-contract) API and Kalshi recommends a **separate API key** for
it. It is therefore exposed through standalone :class:`PerpsClient` /
:class:`AsyncPerpsClient` classes with their own :class:`PerpsConfig`.

Perps model and resource classes are exported from this package namespace
(``kalshi.perps``) rather than the top-level ``kalshi`` namespace, because many
perps schema names are intentional twins of the prediction-API models and would
collide in ``kalshi.__all__``. Only the headline entry points (``PerpsClient`` /
``AsyncPerpsClient`` / ``PerpsConfig``) are re-exported from ``kalshi``.
"""

from __future__ import annotations

from kalshi.perps.async_client import AsyncPerpsClient
from kalshi.perps.client import PerpsClient
from kalshi.perps.config import (
    PERPS_DEMO_BASE_URL,
    PERPS_DEMO_WS_URL,
    PERPS_PRODUCTION_BASE_URL,
    PERPS_PRODUCTION_WS_URL,
    PerpsConfig,
)
from kalshi.perps.klear import (
    AsyncKlearClient,
    Error,
    KlearAuth,
    KlearClient,
    KlearConfig,
)
from kalshi.perps.klear.models.margin import (
    FundingPaymentDetail,
    GetActiveMarginObligationsResponse,
    GetGuarantyFundBalanceResponse,
    GetMarginReportsResponse,
    GetObligationFundingPaymentsResponse,
    GetObligationHistoryResponse,
    GetObligationMaintenanceMarginDetailsResponse,
    GetObligationSettlementDetailsResponse,
    GetSettlementBalanceHistoryResponse,
    GetSettlementBalanceResponse,
    GetSettlementBalanceWithdrawalResponse,
    GetSettlementEstimateByAssetClassResponse,
    MaintenanceMarginDetail,
    MarginReport,
    MarginReportTypeLiteral,
    MarketSettlementEstimate,
    ObligationEntry,
    ObligationReceiveInfo,
    SettlementBalanceHistoryEntry,
    SettlementDetail,
    SettlementEstimate,
    WithdrawalStatusLiteral,
    WithdrawSettlementBalanceRequest,
    WithdrawSettlementBalanceResponse,
)
from kalshi.perps.klear.resources.margin import (
    AsyncMarginResource,
    MarginResource,
)
from kalshi.perps.models.common import (
    BookSide,
    EmptyResponse,
    ErrorResponse,
    ExchangeIndex,
    ExchangeInstance,
    LastUpdateReason,
    MarginMarketStatus,
    OrderSource,
    PriceLevelDollarsCountFp,
    SelfTradePreventionType,
)
from kalshi.perps.models.exchange import (
    ExchangeStatus,
    GetMarginRiskParametersResponse,
    MarginEnabledResponse,
)
from kalshi.perps.models.fcm import (
    FCMAssetClassLiteral,
    FCMSubtraderRiskControls,
    GetFCMSubtraderRiskControlsResponse,
    UpdateFCMSubtraderRiskControlsRequest,
)
from kalshi.perps.models.funding import (
    MarginFundingHistoryEntry,
    MarginFundingRate,
    MarginFundingRateEstimate,
)
from kalshi.perps.models.margin_account import (
    FeeScheduleLiteral,
    GetMarginBalanceResponse,
    GetMarginFeeTierRatesResponse,
    GetMarginFeeTiersResponse,
    GetMarginRiskResponse,
    MarginFeeTierRate,
    MarginRiskPosition,
    MarginSubaccountBalance,
    NotionalRiskLimitResponse,
)
from kalshi.perps.models.markets import (
    BidAskDistributionHistorical,
    MarginMarket,
    MarginMarketCandlestick,
    MarginMarketSchedule,
    MarginMarketStatusLiteral,
    MarginOrderbook,
    MarginOrderbookLevel,
    PriceDistributionHistorical,
)
from kalshi.perps.models.order_groups import (
    CreateOrderGroupRequest,
    CreateOrderGroupResponse,
    GetOrderGroupResponse,
    OrderGroup,
    UpdateOrderGroupLimitRequest,
)
from kalshi.perps.models.orders import (
    AmendMarginOrderRequest,
    AmendMarginOrderResponse,
    BookSideLiteral,
    CancelMarginOrderResponse,
    CreateMarginOrderRequest,
    CreateMarginOrderResponse,
    DecreaseMarginOrderRequest,
    DecreaseMarginOrderResponse,
    GetMarginOrderResponse,
    GetMarginOrdersResponse,
    LastUpdateReasonLiteral,
    MarginOrder,
    OrderSourceLiteral,
    SelfTradePreventionTypeLiteral,
    TimeInForceLiteral,
)
from kalshi.perps.models.portfolio import (
    ExitTrigger,
    ExitTriggerKindLiteral,
    ExitTriggerLegLiteral,
    ExitTriggerReasonLiteral,
    ExitTriggerStatusLiteral,
    GetExitTriggersResponse,
    GetMarginFillsResponse,
    GetMarginPositionsResponse,
    GetMarginTradesResponse,
    MarginFill,
    MarginPosition,
    MarginTrade,
    SetCrossExitTriggerRequest,
    SetIsolatedExitTriggerRequest,
    UpdateExitTriggerRequest,
)
from kalshi.perps.models.transfers import (
    ApplySubaccountTransferRequest,
    CreateSubaccountResponse,
    ExchangeInstanceLiteral,
    IntraExchangeInstanceTransferRequest,
    IntraExchangeInstanceTransferResponse,
)
from kalshi.perps.resources.exchange import (
    AsyncPerpsExchangeResource,
    PerpsExchangeResource,
)
from kalshi.perps.resources.funding import (
    AsyncFundingResource,
    FundingResource,
)
from kalshi.perps.resources.margin_account import (
    AsyncMarginAccountResource,
    MarginAccountResource,
)
from kalshi.perps.resources.markets import (
    AsyncPerpsMarketsResource,
    PerpsMarketsResource,
)
from kalshi.perps.resources.order_groups import (
    AsyncOrderGroupsResource,
    OrderGroupsResource,
)
from kalshi.perps.resources.orders import (
    AsyncMarginOrdersResource,
    MarginOrdersResource,
)
from kalshi.perps.resources.portfolio import (
    AsyncPerpsPortfolioResource,
    PerpsPortfolioResource,
)
from kalshi.perps.resources.transfers import (
    AsyncTransfersResource,
    TransfersResource,
)
from kalshi.perps.ws import (
    ConnectionState,
    MessageQueue,
    OverflowStrategy,
    PerpsConnectionManager,
    PerpsWebSocket,
)
from kalshi.perps.ws.models import (
    FundingRate,
    MarginFillMessage,
    MarginFillPayload,
    MarginOrderbookDeltaMessage,
    MarginOrderbookDeltaPayload,
    MarginOrderbookSnapshotMessage,
    MarginOrderbookSnapshotPayload,
    MarginTickerMessage,
    MarginTickerPayload,
    MarginTradeMessage,
    MarginTradePayload,
    MarginUserOrderMessage,
    MarginUserOrderPayload,
    OrderGroupEventType,
    OrderGroupUpdatesMessage,
    OrderGroupUpdatesPayload,
    PerpsBookSide,
    PerpsChannel,
    PerpsLastUpdateReason,
    PerpsSelfTradePreventionType,
    TickerPrice,
    UpdateSubscriptionAction,
)

__all__ = [
    "PERPS_DEMO_BASE_URL",
    "PERPS_DEMO_WS_URL",
    "PERPS_PRODUCTION_BASE_URL",
    "PERPS_PRODUCTION_WS_URL",
    "AmendMarginOrderRequest",
    "AmendMarginOrderResponse",
    "ApplySubaccountTransferRequest",
    "AsyncFundingResource",
    "AsyncKlearClient",
    "AsyncMarginAccountResource",
    "AsyncMarginOrdersResource",
    "AsyncMarginResource",
    "AsyncOrderGroupsResource",
    "AsyncPerpsClient",
    "AsyncPerpsExchangeResource",
    "AsyncPerpsMarketsResource",
    "AsyncPerpsPortfolioResource",
    "AsyncTransfersResource",
    "BidAskDistributionHistorical",
    "BookSide",
    "BookSideLiteral",
    "CancelMarginOrderResponse",
    "ConnectionState",
    "CreateMarginOrderRequest",
    "CreateMarginOrderResponse",
    "CreateOrderGroupRequest",
    "CreateOrderGroupResponse",
    "CreateSubaccountResponse",
    "DecreaseMarginOrderRequest",
    "DecreaseMarginOrderResponse",
    "EmptyResponse",
    "Error",
    "ErrorResponse",
    "ExchangeIndex",
    "ExchangeInstance",
    "ExchangeInstanceLiteral",
    "ExchangeStatus",
    "ExitTrigger",
    "ExitTriggerKindLiteral",
    "ExitTriggerLegLiteral",
    "ExitTriggerReasonLiteral",
    "ExitTriggerStatusLiteral",
    "FCMAssetClassLiteral",
    "FCMSubtraderRiskControls",
    "FeeScheduleLiteral",
    "FundingPaymentDetail",
    "FundingRate",
    "FundingResource",
    "GetActiveMarginObligationsResponse",
    "GetExitTriggersResponse",
    "GetFCMSubtraderRiskControlsResponse",
    "GetGuarantyFundBalanceResponse",
    "GetMarginBalanceResponse",
    "GetMarginFeeTierRatesResponse",
    "GetMarginFeeTiersResponse",
    "GetMarginFillsResponse",
    "GetMarginOrderResponse",
    "GetMarginOrdersResponse",
    "GetMarginPositionsResponse",
    "GetMarginReportsResponse",
    "GetMarginRiskParametersResponse",
    "GetMarginRiskResponse",
    "GetMarginTradesResponse",
    "GetObligationFundingPaymentsResponse",
    "GetObligationHistoryResponse",
    "GetObligationMaintenanceMarginDetailsResponse",
    "GetObligationSettlementDetailsResponse",
    "GetOrderGroupResponse",
    "GetSettlementBalanceHistoryResponse",
    "GetSettlementBalanceResponse",
    "GetSettlementBalanceWithdrawalResponse",
    "GetSettlementEstimateByAssetClassResponse",
    "IntraExchangeInstanceTransferRequest",
    "IntraExchangeInstanceTransferResponse",
    "KlearAuth",
    "KlearClient",
    "KlearConfig",
    "LastUpdateReason",
    "LastUpdateReasonLiteral",
    "MaintenanceMarginDetail",
    "MarginAccountResource",
    "MarginEnabledResponse",
    "MarginFeeTierRate",
    "MarginFill",
    "MarginFillMessage",
    "MarginFillPayload",
    "MarginFundingHistoryEntry",
    "MarginFundingRate",
    "MarginFundingRateEstimate",
    "MarginMarket",
    "MarginMarketCandlestick",
    "MarginMarketSchedule",
    "MarginMarketStatus",
    "MarginMarketStatusLiteral",
    "MarginOrder",
    "MarginOrderbook",
    "MarginOrderbookDeltaMessage",
    "MarginOrderbookDeltaPayload",
    "MarginOrderbookLevel",
    "MarginOrderbookSnapshotMessage",
    "MarginOrderbookSnapshotPayload",
    "MarginOrdersResource",
    "MarginPosition",
    "MarginReport",
    "MarginReportTypeLiteral",
    "MarginResource",
    "MarginRiskPosition",
    "MarginSubaccountBalance",
    "MarginTickerMessage",
    "MarginTickerPayload",
    "MarginTrade",
    "MarginTradeMessage",
    "MarginTradePayload",
    "MarginUserOrderMessage",
    "MarginUserOrderPayload",
    "MarketSettlementEstimate",
    "MessageQueue",
    "NotionalRiskLimitResponse",
    "ObligationEntry",
    "ObligationReceiveInfo",
    "OrderGroup",
    "OrderGroupEventType",
    "OrderGroupUpdatesMessage",
    "OrderGroupUpdatesPayload",
    "OrderGroupsResource",
    "OrderSource",
    "OrderSourceLiteral",
    "OverflowStrategy",
    "PerpsBookSide",
    "PerpsChannel",
    "PerpsClient",
    "PerpsConfig",
    "PerpsConnectionManager",
    "PerpsExchangeResource",
    "PerpsLastUpdateReason",
    "PerpsMarketsResource",
    "PerpsPortfolioResource",
    "PerpsSelfTradePreventionType",
    "PerpsWebSocket",
    "PriceDistributionHistorical",
    "PriceLevelDollarsCountFp",
    "SelfTradePreventionType",
    "SelfTradePreventionTypeLiteral",
    "SetCrossExitTriggerRequest",
    "SetIsolatedExitTriggerRequest",
    "SettlementBalanceHistoryEntry",
    "SettlementDetail",
    "SettlementEstimate",
    "TickerPrice",
    "TimeInForceLiteral",
    "TransfersResource",
    "UpdateExitTriggerRequest",
    "UpdateFCMSubtraderRiskControlsRequest",
    "UpdateOrderGroupLimitRequest",
    "UpdateSubscriptionAction",
    "WithdrawSettlementBalanceRequest",
    "WithdrawSettlementBalanceResponse",
    "WithdrawalStatusLiteral",
]
